version: "3.7"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile-static-server
    ports:
      - "8080:8080"
    volumes:
      - ./static-server/static:/static
    depends_on:
      - "api"
  api:
    build: .
    environment:
      - LOG_LEVEL=trace
      - DB_PORT=5432
      - DB_PASSWORD=pwd0123456789
      - DB_HOST=postgres://db
    ports:
      - "8081:8081"
    depends_on:
      - "db"
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=pwd0123456789
      - POSTGRES_DB=api
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data